/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SessionId = IDL.Text;
export const ClassId = IDL.Text;
export const StudentId = IDL.Text;
export const TeacherId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CircularId = IDL.Nat;
export const TimetableEntry = IDL.Record({
  'day' : IDL.Text,
  'periodName' : IDL.Text,
  'periodNumber' : IDL.Nat,
});
export const TimetableId = IDL.Nat;
export const Circular = IDL.Record({
  'id' : CircularId,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'sessionId' : SessionId,
  'attachments' : IDL.Vec(ExternalBlob),
  'classIds' : IDL.Vec(ClassId),
});
export const Class = IDL.Record({
  'id' : ClassId,
  'students' : IDL.Vec(StudentId),
  'name' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : SessionId,
  'name' : IDL.Text,
  'classes' : IDL.Vec(Class),
});
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'name' : IDL.Text,
  'classId' : ClassId,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'schoolCode' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'name' : IDL.Text,
  'classId' : ClassId,
  'admissionNo' : IDL.Text,
});
export const Timetable = IDL.Record({
  'id' : TimetableId,
  'classId' : ClassId,
  'entries' : IDL.Vec(TimetableEntry),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClassToSession' : IDL.Func(
      [SessionId, ClassId, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addStudent' : IDL.Func(
      [StudentId, IDL.Text, IDL.Text, ClassId],
      [StudentId],
      [],
    ),
  'addTeacher' : IDL.Func([TeacherId, IDL.Text, ClassId], [TeacherId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCircular' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), SessionId, IDL.Vec(ClassId)],
      [CircularId],
      [],
    ),
  'createSession' : IDL.Func([IDL.Text], [SessionId], []),
  'createTimetable' : IDL.Func(
      [ClassId, IDL.Vec(TimetableEntry)],
      [TimetableId],
      [],
    ),
  'deleteCircular' : IDL.Func([CircularId], [], []),
  'deleteStudent' : IDL.Func([StudentId], [], []),
  'deleteTeacher' : IDL.Func([TeacherId], [], []),
  'getAllCirculars' : IDL.Func([], [IDL.Vec(Circular)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentsByClass' : IDL.Func([ClassId], [IDL.Vec(Student)], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
  'getTimetable' : IDL.Func([ClassId], [IDL.Opt(Timetable)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCircular' : IDL.Func(
      [
        CircularId,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        SessionId,
        IDL.Vec(ClassId),
      ],
      [IDL.Bool],
      [],
    ),
  'updateStudent' : IDL.Func(
      [StudentId, IDL.Text, IDL.Text, ClassId],
      [IDL.Bool],
      [],
    ),
  'updateTeacher' : IDL.Func([TeacherId, IDL.Text, ClassId], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SessionId = IDL.Text;
  const ClassId = IDL.Text;
  const StudentId = IDL.Text;
  const TeacherId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CircularId = IDL.Nat;
  const TimetableEntry = IDL.Record({
    'day' : IDL.Text,
    'periodName' : IDL.Text,
    'periodNumber' : IDL.Nat,
  });
  const TimetableId = IDL.Nat;
  const Circular = IDL.Record({
    'id' : CircularId,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'sessionId' : SessionId,
    'attachments' : IDL.Vec(ExternalBlob),
    'classIds' : IDL.Vec(ClassId),
  });
  const Class = IDL.Record({
    'id' : ClassId,
    'students' : IDL.Vec(StudentId),
    'name' : IDL.Text,
  });
  const Session = IDL.Record({
    'id' : SessionId,
    'name' : IDL.Text,
    'classes' : IDL.Vec(Class),
  });
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'name' : IDL.Text,
    'classId' : ClassId,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'schoolCode' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'name' : IDL.Text,
    'classId' : ClassId,
    'admissionNo' : IDL.Text,
  });
  const Timetable = IDL.Record({
    'id' : TimetableId,
    'classId' : ClassId,
    'entries' : IDL.Vec(TimetableEntry),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClassToSession' : IDL.Func(
        [SessionId, ClassId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addStudent' : IDL.Func(
        [StudentId, IDL.Text, IDL.Text, ClassId],
        [StudentId],
        [],
      ),
    'addTeacher' : IDL.Func([TeacherId, IDL.Text, ClassId], [TeacherId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCircular' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          SessionId,
          IDL.Vec(ClassId),
        ],
        [CircularId],
        [],
      ),
    'createSession' : IDL.Func([IDL.Text], [SessionId], []),
    'createTimetable' : IDL.Func(
        [ClassId, IDL.Vec(TimetableEntry)],
        [TimetableId],
        [],
      ),
    'deleteCircular' : IDL.Func([CircularId], [], []),
    'deleteStudent' : IDL.Func([StudentId], [], []),
    'deleteTeacher' : IDL.Func([TeacherId], [], []),
    'getAllCirculars' : IDL.Func([], [IDL.Vec(Circular)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentsByClass' : IDL.Func([ClassId], [IDL.Vec(Student)], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
    'getTimetable' : IDL.Func([ClassId], [IDL.Opt(Timetable)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCircular' : IDL.Func(
        [
          CircularId,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          SessionId,
          IDL.Vec(ClassId),
        ],
        [IDL.Bool],
        [],
      ),
    'updateStudent' : IDL.Func(
        [StudentId, IDL.Text, IDL.Text, ClassId],
        [IDL.Bool],
        [],
      ),
    'updateTeacher' : IDL.Func([TeacherId, IDL.Text, ClassId], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };