/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Circular {
  'id' : CircularId,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'sessionId' : SessionId,
  'attachments' : Array<ExternalBlob>,
  'classIds' : Array<ClassId>,
}
export type CircularId = bigint;
export interface Class {
  'id' : ClassId,
  'students' : Array<StudentId>,
  'name' : string,
}
export type ClassId = string;
export type ExternalBlob = Uint8Array;
export interface Session {
  'id' : SessionId,
  'name' : string,
  'classes' : Array<Class>,
}
export type SessionId = string;
export interface Student {
  'id' : StudentId,
  'name' : string,
  'classId' : ClassId,
  'admissionNo' : string,
}
export type StudentId = string;
export interface Teacher {
  'id' : TeacherId,
  'name' : string,
  'classId' : ClassId,
}
export type TeacherId = string;
export interface Timetable {
  'id' : TimetableId,
  'classId' : ClassId,
  'entries' : Array<TimetableEntry>,
}
export interface TimetableEntry {
  'day' : string,
  'periodName' : string,
  'periodNumber' : bigint,
}
export type TimetableId = bigint;
export interface UserProfile {
  'username' : string,
  'name' : string,
  'role' : string,
  'schoolCode' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClassToSession' : ActorMethod<[SessionId, ClassId, string], boolean>,
  'addStudent' : ActorMethod<[StudentId, string, string, ClassId], StudentId>,
  'addTeacher' : ActorMethod<[TeacherId, string, ClassId], TeacherId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCircular' : ActorMethod<
    [string, string, Array<ExternalBlob>, SessionId, Array<ClassId>],
    CircularId
  >,
  'createSession' : ActorMethod<[string], SessionId>,
  'createTimetable' : ActorMethod<
    [ClassId, Array<TimetableEntry>],
    TimetableId
  >,
  'deleteCircular' : ActorMethod<[CircularId], undefined>,
  'deleteStudent' : ActorMethod<[StudentId], undefined>,
  'deleteTeacher' : ActorMethod<[TeacherId], undefined>,
  'getAllCirculars' : ActorMethod<[], Array<Circular>>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentsByClass' : ActorMethod<[ClassId], Array<Student>>,
  'getTeacher' : ActorMethod<[TeacherId], [] | [Teacher]>,
  'getTimetable' : ActorMethod<[ClassId], [] | [Timetable]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCircular' : ActorMethod<
    [
      CircularId,
      string,
      string,
      Array<ExternalBlob>,
      SessionId,
      Array<ClassId>,
    ],
    boolean
  >,
  'updateStudent' : ActorMethod<[StudentId, string, string, ClassId], boolean>,
  'updateTeacher' : ActorMethod<[TeacherId, string, ClassId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];